import { createHash,randomUUID } from "node:crypto";

import { base64Tool,base64ToolInputSchema,colorConverter,colorConverterInputSchema,dateMath,dateMathInputSchema,hashTextInputSchema,jsonTool,jsonToolInputSchema,markdownTable,markdownTableInputSchema,slugifyText,slugifyTextInputSchema,textStats,textStatsInputSchema,unitConverter,unitConverterInputSchema,uuidGeneratorInputSchema } from "./builtin-tool-primitives";
import { BuiltInToolDefinition } from "./builtin-tools.built-in-tool-execution-context";
export const builtInToolsPart3 = [
  {
    id: "00000000-0000-4000-8000-000000000007",
    name: "uuid_generator",
    displayName: "UUID generator",
    description: "Generate UUIDs for IDs, examples, and test data.",
    riskLevel: "low",
    category: "Create",
    inputSchema: uuidGeneratorInputSchema,
    execute: ({ count }) => {
      const values = Array.from({ length: count }, () => randomUUID());
      return { values, value: values[0] };
    },
  },
  {
    id: "00000000-0000-4000-8000-000000000008",
    name: "date_math",
    displayName: "Date math",
    description: "Add, subtract, or compare dates.",
    riskLevel: "low",
    category: "Time",
    inputSchema: dateMathInputSchema,
    execute: dateMath,
  },
  {
    id: "00000000-0000-4000-8000-000000000009",
    name: "json_tool",
    displayName: "JSON helper",
    description: "Validate, format, minify, or inspect JSON.",
    riskLevel: "low",
    category: "Code",
    inputSchema: jsonToolInputSchema,
    execute: jsonTool,
  },
  {
    id: "00000000-0000-4000-8000-000000000010",
    name: "text_stats",
    displayName: "Text stats",
    description: "Count words, characters, lines, and reading time.",
    riskLevel: "low",
    category: "Write",
    inputSchema: textStatsInputSchema,
    execute: textStats,
  },
  {
    id: "00000000-0000-4000-8000-000000000011",
    name: "base64_tool",
    displayName: "Base64",
    description: "Encode or decode Base64 text.",
    riskLevel: "low",
    category: "Code",
    inputSchema: base64ToolInputSchema,
    execute: base64Tool,
  },
  {
    id: "00000000-0000-4000-8000-000000000012",
    name: "hash_text",
    displayName: "Hash text",
    description: "Create SHA-256, SHA-1, or MD5 hashes.",
    riskLevel: "low",
    category: "Code",
    inputSchema: hashTextInputSchema,
    execute: ({ text, algorithm }) => ({
      algorithm,
      hash: createHash(algorithm).update(text).digest("hex"),
    }),
  },
  {
    id: "00000000-0000-4000-8000-000000000013",
    name: "unit_converter",
    displayName: "Unit converter",
    description: "Convert length, weight, data, and temperature units.",
    riskLevel: "low",
    category: "Think",
    inputSchema: unitConverterInputSchema,
    execute: unitConverter,
  },
  {
    id: "00000000-0000-4000-8000-000000000014",
    name: "slugify_text",
    displayName: "Slugify text",
    description: "Turn text into clean URL/file slugs.",
    riskLevel: "low",
    category: "Write",
    inputSchema: slugifyTextInputSchema,
    execute: slugifyText,
  },
  {
    id: "00000000-0000-4000-8000-000000000015",
    name: "color_converter",
    displayName: "Color converter",
    description: "Convert hex colors to RGB and HSL.",
    riskLevel: "low",
    category: "Design",
    inputSchema: colorConverterInputSchema,
    execute: colorConverter,
  },
  {
    id: "00000000-0000-4000-8000-000000000016",
    name: "markdown_table",
    displayName: "Markdown table",
    description: "Create a clean Markdown table from columns and rows.",
    riskLevel: "low",
    category: "Write",
    inputSchema: markdownTableInputSchema,
    execute: markdownTable,
  },
] satisfies BuiltInToolDefinition[];
