import { TITLE_FIELD } from "./builtin-tool-json-schema.fallback-schema";
export const commonSchemasPart3 = {
  create_spreadsheet: {
    type: "object",
    properties: {
      title: { type: "string" },
      summary: { type: "string" },
      columns: { type: "array", items: { type: "string" } },
      rows: {
        type: "array",
        items: { type: "array", items: { type: "string" } },
      },
      insights: { type: "array", items: { type: "string" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD, "columns", "rows"],
  },
  create_meeting_brief: {
    type: "object",
    properties: {
      title: { type: "string" },
      date: { type: "string" },
      attendees: { type: "array", items: { type: "string" } },
      objective: { type: "string" },
      agenda: { type: "array", items: { type: "string" } },
      decisions: { type: "array", items: { type: "string" } },
      actionItems: { type: "array", items: { type: "object" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD],
  },
  create_action_plan: {
    type: "object",
    properties: {
      title: { type: "string" },
      objective: { type: "string" },
      phases: { type: "array", items: { type: "object" } },
      actionItems: { type: "array", items: { type: "object" } },
      risks: { type: "array", items: { type: "string" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD, "phases"],
  },
  create_decision_matrix: {
    type: "object",
    properties: {
      title: { type: "string" },
      context: { type: "string" },
      criteria: { type: "array", items: { type: "object" } },
      options: { type: "array", items: { type: "object" } },
      recommendation: { type: "string" },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD, "criteria", "options"],
  },
  create_email_pack: {
    type: "object",
    properties: {
      title: { type: "string" },
      goal: { type: "string" },
      audience: { type: "string" },
      tone: {
        type: "string",
        enum: ["direct", "friendly", "executive", "sales", "support"],
      },
      emails: { type: "array", items: { type: "object" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD, "emails"],
  },
  create_project_status_report: {
    type: "object",
    properties: {
      title: { type: "string" },
      reportingPeriod: { type: "string" },
      overallStatus: {
        type: "string",
        enum: ["green", "yellow", "red", "blocked"],
        default: "green",
      },
      executiveSummary: { type: "string" },
      metrics: { type: "array", items: { type: "object" } },
      milestones: { type: "array", items: { type: "object" } },
      blockers: { type: "array", items: { type: "string" } },
      decisionsNeeded: { type: "array", items: { type: "string" } },
      nextSteps: { type: "array", items: { type: "object" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD],
  },
  create_risk_register: {
    type: "object",
    properties: {
      title: { type: "string" },
      context: { type: "string" },
      risks: { type: "array", items: { type: "object" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD, "risks"],
  },
  create_raci_matrix: {
    type: "object",
    properties: {
      title: { type: "string" },
      context: { type: "string" },
      roles: { type: "array", items: { type: "string" } },
      activities: { type: "array", items: { type: "object" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD, "roles", "activities"],
  },
  create_customer_account_plan: {
    type: "object",
    properties: {
      title: { type: "string" },
      accountName: { type: "string" },
      objective: { type: "string" },
      stakeholders: { type: "array", items: { type: "object" } },
      opportunities: { type: "array", items: { type: "object" } },
      risks: { type: "array", items: { type: "string" } },
      nextActions: { type: "array", items: { type: "object" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD, "accountName"],
  },
  create_competitive_battlecard: {
    type: "object",
    properties: {
      title: { type: "string" },
      competitor: { type: "string" },
      positioning: { type: "string" },
      winThemes: { type: "array", items: { type: "string" } },
      strengths: { type: "array", items: { type: "string" } },
      weaknesses: { type: "array", items: { type: "string" } },
      landmines: { type: "array", items: { type: "string" } },
      objectionHandling: { type: "array", items: { type: "object" } },
      discoveryQuestions: { type: "array", items: { type: "string" } },
      height: { type: "number", default: 620 },
    },
    required: [TITLE_FIELD, "competitor"],
  },
  random_number: {
    type: "object",
    properties: {
      min: { type: "number", default: 0 },
      max: { type: "number", default: 100 },
      count: { type: "number", default: 1, minimum: 1, maximum: 100 },
      integer: { type: "boolean", default: true },
    },
    required: [],
  },
  uuid_generator: {
    type: "object",
    properties: {
      count: { type: "number", default: 1, minimum: 1, maximum: 50 },
    },
    required: [],
  },
  date_math: {
    type: "object",
    properties: {
      operation: { type: "string", enum: ["add", "subtract", "difference"] },
      date: { type: "string", description: "Start date, e.g. 2026-06-08" },
      endDate: { type: "string", description: "End date for difference" },
      amount: { type: "number", default: 0 },
      unit: {
        type: "string",
        enum: ["days", "weeks", "months", "years"],
        default: "days",
      },
    },
    required: ["operation", "date"],
  },
};
